

export const THEME = {
    PRIMARY_COLOR: '#354750',
    SECONDARY_COLOR: '#8ABD0F',

    LIGHT_TEXT_MAIN: '#455A64',
    LIGHT_TEXT_SECONDARY: '#70858F',
    LIGHT_TEXT_LIGHT: '#90A4AE',
    LIGHT_MAIN: '#ffffff',
    LIGHT_SECONDARY: '#F3F5F5',
    LIGHT_LIGHT: '#F2F4F4',
    LIGHT_DROPDOWN_LIGHT: '#ffffff',
    LIGHT_BUTTON: '#8ABD0F',
    LIGHT_BUTTON_TEXT: '#ffffff',
    LIGHT_SIMPLE_BUTTON_TEXT: '#8ABD0F',
    LIGHT_TABLEROW: '#FAFBFB',
    LIGHT_TABLEROW_SECONDARY: '#ffffff',
    LIGHT_TABLEROW_HEAD: '#f6f7f8',
    LIGHT_TABLEROW_HOVER: '#C4F056',
    LIGHT_SIDENAV_ACTIVE: '#C4F056',
    LIGHT_MODAL_HEAD: '#E9EDEF',
    LIGHT_MODAL_BODY: '#ffffff',
    LIGHT_INPUT: '#ffffff',
    LIGHT_DROPDOWN: '#ffffff',
    LIGHT_BORDER: '#E9EDEF',
    LIGHT_ACTIVE: '#6d960c',
    LIGHT_ICON: '#70858F',
    LIGHT_DATE: '#F2F4F4',
    LIGHT_DATE_TEXT: '#455A64',
    LIGHT_CHECKBOX: '#90A4AE',
    LIGHT_VIEWER: '#F5F7F8',
    LIGHT_GUTTER: '#70858F',
    LIGHT_BORDER_LIGHT: '#E5E6E7',
    LIGHT_TAB: '#FAFAFA',

    DARK_TEXT_MAIN: '#E9EDEF',
    DARK_TEXT_SECONDARY: '#90A4AE',
    DARK_TEXT_LIGHT: '#90A4AE',
    DARK_MAIN: '#2D3035',
    DARK_SECONDARY: '#1F2123',
    DARK_LIGHT: '#424449',
    DARK_BUTTON: '#EFEFEF',
    DARK_BUTTON_TEXT: '#455A64',
    DARK_SIMPLE_BUTTON_TEXT: '#E9EDEF',
    DARK_TABLEROW: '#2D3035',
    DARK_TABLEROW_SECONDARY: '#313438',
    DARK_TABLEROW_HEAD: '#313438',
    DARK_TABLEROW_HOVER: '#424449',
    DARK_SIDENAV_ACTIVE:'#424449',
    DARK_MODAL_HEAD: '#424449',
    DARK_MODAL_BODY: '#2D3035',
    DARK_INPUT: '#424449',
    DARK_DROPDOWN: '#424449',
    DARK_BORDER: '#2D3035',
    DARK_ACTIVE: '#90A4AE',
    DARK_ICON: '#90A4AE',
    DARK_DATE: '#424449',
    DARK_DATE_TEXT: '#90A4AE',
    DARK_CHECKBOX: '#90A4AE',
    DARK_VIEWER: '#2D3035',
    DARK_GUTTER: '#90A4AE',
    DARK_BORDER_LIGHT: '#1F2123',
    DARK_TAB: '#2D3035',
}

export const lightTheme = {
    '--color-primary': THEME.PRIMARY_COLOR,
    '--color-secondary': THEME.SECONDARY_COLOR,
    '--color-textmain': THEME.LIGHT_TEXT_MAIN,
    '--color-textsecondary': THEME.LIGHT_TEXT_SECONDARY,
    '--color-textlight': THEME.LIGHT_TEXT_LIGHT,
    '--color-maincolor': THEME.LIGHT_MAIN,
    '--color-secondarycolor': THEME.LIGHT_SECONDARY,
    '--color-lightcolor': THEME.LIGHT_LIGHT,
    '--color-lightcolordropdown': THEME.LIGHT_DROPDOWN_LIGHT,
    '--color-buttoncolor': THEME.LIGHT_BUTTON,
    '--color-buttoncolortext': THEME.LIGHT_BUTTON_TEXT,
    '--color-buttoncolortextsimple': THEME.LIGHT_SIMPLE_BUTTON_TEXT,
    '--color-tablerow': THEME.LIGHT_TABLEROW,
    '--color-tablerowsecondary': THEME.LIGHT_TABLEROW_SECONDARY,
    '--color-tablerowhead': THEME.LIGHT_TABLEROW_HEAD,
    '--color-rowhover': THEME.LIGHT_TABLEROW_HOVER,
    '--color-sidenavactive': THEME.LIGHT_SIDENAV_ACTIVE,
    '--color-modalhead': THEME.LIGHT_MODAL_HEAD,
    '--color-modalbody': THEME.LIGHT_MODAL_BODY,
    '--color-input': THEME.LIGHT_INPUT,
    '--color-dropdowncolor': THEME.LIGHT_DROPDOWN,
    '--color-bordercolor': THEME.LIGHT_BORDER,
    '--color-menuaitem': THEME.LIGHT_ACTIVE,
    '--color-iconcolor': THEME.LIGHT_ICON,
    '--color-datecolor': THEME.LIGHT_DATE,
    '--color-datetext': THEME.LIGHT_DATE_TEXT,
    '--color-checkbox': THEME.LIGHT_CHECKBOX,
    '--color-viewer': THEME.LIGHT_VIEWER,
    '--color-gutter': THEME.LIGHT_GUTTER,
    '--color-borderlight': THEME.LIGHT_BORDER_LIGHT,
    '--color-tab': THEME.LIGHT_TAB,
  }
  
  export const darkTheme = {
    '--color-primary': THEME.PRIMARY_COLOR,
    '--color-secondary': THEME.SECONDARY_COLOR,
    '--color-textmain': THEME.DARK_TEXT_MAIN,
    '--color-textsecondary': THEME.DARK_TEXT_SECONDARY,
    '--color-textlight': THEME.DARK_TEXT_LIGHT,
    '--color-maincolor': THEME.DARK_MAIN,
    '--color-secondarycolor': THEME.DARK_SECONDARY,
    '--color-lightcolor': THEME.DARK_LIGHT,
    '--color-lightcolordropdown': THEME.DARK_LIGHT,
    '--color-buttoncolor': THEME.DARK_BUTTON,
    '--color-buttoncolortext': THEME.DARK_BUTTON_TEXT,
    '--color-buttoncolortextsimple': THEME.DARK_SIMPLE_BUTTON_TEXT,
    '--color-tablerow': THEME.DARK_TABLEROW,
    '--color-tablerowsecondary': THEME.DARK_TABLEROW_SECONDARY,
    '--color-tablerowhead': THEME.DARK_TABLEROW_HEAD,
    '--color-rowhover': THEME.DARK_TABLEROW_HOVER,
    '--color-sidenavactive': THEME.DARK_SIDENAV_ACTIVE,
    '--color-modalhead': THEME.DARK_MODAL_HEAD,
    '--color-modalbody': THEME.DARK_MODAL_BODY,
    '--color-input': THEME.DARK_INPUT,
    '--color-dropdowncolor': THEME.DARK_DROPDOWN,
    '--color-bordercolor': THEME.DARK_BORDER,
    '--color-menuaitem': THEME.DARK_ACTIVE,
    '--color-iconcolor': THEME.DARK_ICON,
    '--color-datecolor': THEME.DARK_DATE,
    '--color-datetext': THEME.DARK_DATE_TEXT,
    '--color-checkbox': THEME.DARK_CHECKBOX,
    '--color-viewer': THEME.DARK_VIEWER,
    '--color-gutter': THEME.DARK_GUTTER,
    '--color-borderlight': THEME.DARK_BORDER_LIGHT,
    '--color-tab': THEME.DARK_TAB,
  }